### ISSUE TITLE
pom.xml empty after latest commit

### ISSUE THREAD

**Issue by vsposato** [Azure-Samples/key-vault-java-manage-key-vaults#5]
It appears that after @daschult made changes for the fluent API - the pom.xml file has been emptied out. I am not sure if this was intentional, but it broke the instructions from this site https://azure.microsoft.com/en-us/resources/samples/key-vault-java-manage-key-vaults/.

**Comment by daschult** [comment]
Thanks for making me aware of this issue. I've fixed it in [this commit](https://github.com/Azure-Samples/key-vault-java-manage-key-vaults/commit/f775bde0789b496f920499bcaae7c7fd2f0c28e8).
